<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-David-Nicolas364/blob/main/Ago11-12/myfirstnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [12]:
lista1=[2,"2","dos", 2.0]

In [21]:
lista1*4

[2,
 '2',
 'tres',
 2.0,
 2,
 '2',
 'tres',
 2.0,
 2,
 '2',
 'tres',
 2.0,
 2,
 '2',
 'tres',
 2.0]

In [18]:
lista2=["4", "cuatro", 4]

In [26]:
lista3=lista1+lista2

In [27]:
lista3

[2, '2', 'tres', 2.0, '4', 'cuatro', 4]

In [13]:
del lista1[2]

In [14]:
lista1

[2, '2', 2.0]

In [15]:
lista1.insert(2, "tres")

In [19]:
lista3=[lista1,lista2]

In [20]:
lista3

[[2, '2', 'tres', 2.0], ['4', 'cuatro', 4]]

In [23]:
for i in lista1:
  print(i)

2
2
tres
2.0


In [25]:
for i in range(len(lista1)):
  print(lista1[i])

2
2
tres
2.0


In [29]:
for i,item in enumerate(lista1):
  print(i,item)

0 2
1 2
2 tres
3 2.0


In [30]:
import array as arr

In [31]:
arreglo = arr.array("i",[1,2,3])

In [32]:
arreglof=arr.array("f",[1,2,3])

In [33]:
nparr1=np.array([1,2,3])
nparr2=np.array([4,5,6])

In [34]:
nparr1*2

array([2, 4, 6])

In [35]:
nparr1*nparr2

array([ 4, 10, 18])

In [36]:
np.dot(nparr1, nparr2)

32

In [37]:
nparr1/nparr2

array([0.25, 0.4 , 0.5 ])