<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-David-Nicolas364/blob/main/Ago11-12/Tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tarea 1 Machine learning

In [3]:
import numpy as np

Nota: Cada elemnto de una lista en python tiene

In [4]:
L = list(range(5))
L

[0, 1, 2, 3, 4]

str() Convierte en String

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4']

Nota: los arrays sólo contienen un tipo de dato

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

El array se convirtió en tipo flotante por el primer elemento

Con dtype se puede poner el tipo del array

In [7]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [16]:
np.array([range(i, i + 4) for i in [2, 4, 6]])

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [17]:
# Se crea un arreglo lleno de 79 3*5
np.full((3, 5), 79)

array([[79, 79, 79, 79, 79],
       [79, 79, 79, 79, 79],
       [79, 79, 79, 79, 79]])

In [18]:
# Empieza en 0, termina en 10, en pasos de 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
# Crea un arrgle de 5 valores separados igualmente entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# Crea un arrglo de 3*3 de números aleatorios distribuidos normalmente
# con media 0 y desviación estándar 1
np.random.normal(0, 1, (3, 3))

array([[-1.48609911,  2.14419981, -0.00397555],
       [-0.39368502,  0.52459424,  0.07882511],
       [-1.50412446, -0.37411854,  0.42928171]])

In [21]:
# Crea un arrglo 3*3 de enteros aleatorios en el intervalo [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 3, 0],
       [0, 4, 4],
       [7, 1, 2]])

In [22]:
#Crea una matriz identidad 3*3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Crea un arrglo sin inicializar de 3 enteros
# Los valores serán lo que se encuentre en la memoria
np.empty(3)

array([1., 1., 1.])

In [5]:
x3 = np.random.randint(10, size=(3, 4, 5))

In [7]:
#Se muestra ndim (tnúmero de dimensiones), shape (tamaño de cada dimensión), and size (el tamaño total del arreglo)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
x3

array([[[1, 9, 3, 8, 0],
        [3, 9, 0, 8, 9],
        [1, 6, 1, 1, 1],
        [4, 7, 6, 2, 0]],

       [[7, 0, 1, 3, 0],
        [8, 6, 4, 8, 7],
        [1, 5, 7, 3, 4],
        [4, 7, 4, 0, 4]],

       [[4, 6, 8, 9, 4],
        [7, 1, 3, 2, 9],
        [0, 8, 2, 8, 7],
        [8, 6, 9, 9, 1]]])

In [10]:
#itemsize, la cual enlista el tamaño (en bytes) de cada elemento del array
#nbytes, en cual enlista el tamaño total (en bytes) del arreglo:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [13]:
#Para indexar desde el  final del arreglo, se pueden usar indices negativos:
x1 = np.random.randint(10, size=6)
x1

array([7, 2, 6, 3, 5, 2])

In [14]:
x1[-1]

2

In [18]:
#Con :: y un valor son todos los valores exceptuando este
x1[::2]

array([7, 6, 5])

In [21]:
# Todos los elementos al revés con valor negativo
x1[::-1]

array([2, 5, 3, 6, 2, 7])

In [4]:
x2 = np.random.randint(10, size=(3, 4))

In [5]:
x2

array([[0, 0, 6, 3],
       [5, 8, 8, 8],
       [3, 6, 4, 4]])

In [7]:
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 5  8]]


In [8]:
x2
#Se puede ver que si se modifica un subarreglo también se modifica el original

array([[99,  0,  6,  3],
       [ 5,  8,  8,  8],
       [ 3,  6,  4,  4]])

In [ ]:
#Usando .copy() se crea una copia que si la modificamos, no se modificará el original
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)