<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-David-Nicolas364/blob/main/Ago11-12/Tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tarea 1 Machine learning

In [ ]:
import numpy as np

In [ ]:
L = list(range(5))
L

[0, 1, 2, 3, 4]

str() Convierte en String

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4']

Nota: los arrays sólo contienen un tipo de dato

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

El array se convirtió en tipo flotante por el primer elemento

Con dtype se puede poner el tipo del array

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([range(i, i + 4) for i in [2, 4, 6]])

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [ ]:
# Se crea un arreglo lleno de 79 3*5
np.full((3, 5), 79)

array([[79, 79, 79, 79, 79],
       [79, 79, 79, 79, 79],
       [79, 79, 79, 79, 79]])

In [ ]:
# Empieza en 0, termina en 10, en pasos de 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
# Crea un arrgle de 5 valores separados igualmente entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Crea un arrglo de 3*3 de números aleatorios distribuidos normalmente
# con media 0 y desviación estándar 1
np.random.normal(0, 1, (3, 3))

array([[-1.48609911,  2.14419981, -0.00397555],
       [-0.39368502,  0.52459424,  0.07882511],
       [-1.50412446, -0.37411854,  0.42928171]])

In [ ]:
# Crea un arrglo 3*3 de enteros aleatorios en el intervalo [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 3, 0],
       [0, 4, 4],
       [7, 1, 2]])

In [ ]:
#Crea una matriz identidad 3*3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Crea un arrglo sin inicializar de 3 enteros
# Los valores serán lo que se encuentre en la memoria
np.empty(3)

array([1., 1., 1.])

In [ ]:
x3 = np.random.randint(10, size=(3, 4, 5))

In [ ]:
#Se muestra ndim (tnúmero de dimensiones), shape (tamaño de cada dimensión), and size (el tamaño total del arreglo)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
x3

array([[[1, 9, 3, 8, 0],
        [3, 9, 0, 8, 9],
        [1, 6, 1, 1, 1],
        [4, 7, 6, 2, 0]],

       [[7, 0, 1, 3, 0],
        [8, 6, 4, 8, 7],
        [1, 5, 7, 3, 4],
        [4, 7, 4, 0, 4]],

       [[4, 6, 8, 9, 4],
        [7, 1, 3, 2, 9],
        [0, 8, 2, 8, 7],
        [8, 6, 9, 9, 1]]])

In [ ]:
#itemsize, la cual enlista el tamaño (en bytes) de cada elemento del array
#nbytes, en cual enlista el tamaño total (en bytes) del arreglo:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
#Para indexar desde el  final del arreglo, se pueden usar indices negativos:
x1 = np.random.randint(10, size=6)
x1

array([7, 2, 6, 3, 5, 2])

In [ ]:
x1[-1]

2

In [ ]:
#Con :: y un valor son todos los valores exceptuando este
x1[::2]

array([7, 6, 5])

In [ ]:
# Todos los elementos al revés con valor negativo
x1[::-1]

array([2, 5, 3, 6, 2, 7])

In [ ]:
x2 = np.random.randint(10, size=(3, 4))

In [ ]:
x2

array([[8, 1, 8, 4],
       [7, 4, 5, 7],
       [6, 6, 1, 0]])

In [ ]:
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 7  4]]


In [ ]:
x2
#Se puede ver que si se modifica un subarreglo también se modifica el original

array([[99,  1,  8,  4],
       [ 7,  4,  5,  7],
       [ 6,  6,  1,  0]])

In [ ]:
#Usando .copy() se crea una copia que si la modificamos, no se modificará el original
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 7  4]]


In [ ]:
# usando np.concatenate se concatenan dos arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# agrupamiento vertical de arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# agrupamiento horizontal de arreglos
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
#Con split se divide un array dependiendo de las posiciones dadas
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [2, 5])
print(x1, x2, x3)

[1 2] [ 3 99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
#numpy puede usar absoluto en números complejos para obtener magnitudes
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [ ]:
#Con power se eleva a una potencia un array
x = [1, 2, 3]
np.power(3, x)

array([ 3,  9, 27])

In [ ]:
#Hay comandos especializados  para mantener un abuena presición
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [ ]:
# con reduce despues del comando de una operación dará el resultado de la suma de todos los elementos del array
x = np.arange(1, 6)
np.add.reduce(x)

15

In [ ]:
np.multiply.reduce(x)

120

In [ ]:
#Con acumulate te mostrará el resultado en cada elemtno del array
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [ ]:
M = np.random.random((3, 4))
print(M)

[[0.491724   0.78775697 0.03749446 0.92660604]
 [0.43167375 0.37623671 0.98815216 0.72562246]
 [0.49189994 0.62989859 0.77759726 0.97965772]]


In [ ]:
#usando axis y cero para que nos de el valor de las columnas
M.min(axis=0)

array([0.43167375, 0.37623671, 0.03749446, 0.72562246])

In [ ]:
#usando axis y uno para que nos de el valor de los renglones
M.max(axis=1)

array([0.92660604, 0.98815216, 0.97965772])

In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [ ]:
#Se estiran tanto a y b para llegar a una forma común
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
#Centrar un arreglo
X = np.random.random((10, 3))

In [ ]:
Xmean = X.mean(0)
Xmean

array([0.44382456, 0.59511793, 0.38074085])

In [ ]:
X_centered = X - Xmean

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
# con count_nonzero se cuentan cuantos elementos cumplen con el criterio
np.count_nonzero(x < 6)

8

In [ ]:
#También con sum
np.sum(x < 6)

8

In [ ]:
# Hay algún calor mayor  que 8?
np.any(x > 8)

True

In [ ]:
# Todos los valores son menores que 10?
np.all(x < 10)

True

In [ ]:
#Se usa una máscara para que sólo nos den un array con los elementos que cumplen la condición
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [ ]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Se usan dos array para el indexado elegante y así seleccionar dependiendo de crenglón y columna
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [ ]:
#El indexado elegante también puede ser usado para cambiar los datos seleccionados
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [ ]:
# argsort() da los índices del orden
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [ ]:
#Partition hace una partición en la que da los números menores a la izquierda y los demás a la derecha del valor dado
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [ ]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))

In [ ]:
#También funciona en arrays de dos dimensiones
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [ ]:
# Se crea un array estructurado con tipos de formatos
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [ ]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]
